import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import {
  SpryZone,
  ZONE_INDEX,
  DISPATCH_CASE_INDEX,
  TIER_PARAMS,
  tierFromIndex,
  feeForDelta,
  marginalFee,
  zoneOf,
  dispatchCase,
  type SpryFeeParams,
} from '../src/index';

// Differential test: the JS port (this package) vs the REAL on-chain Solidity.
//
// The fixture is generated by tools/contract-diff (a forge script that runs the
// actual SmartFeeLib / SpryHook over a grid). Safe/alert/cap and tierParams are
// integer-exact, so they are asserted ==. The danger zone is exponential and the
// JS port uses f64 Math.exp where the contract uses PRB-Math SD59x18, so those
// are allowed a small tolerance; the test also reports the max observed diff.
const DANGER_TOLERANCE_PIPS = 2;

const PARAM_FIELDS = [
  'safeLow',
  'safeHigh',
  'alertLow',
  'alertHigh',
  'dangerLow',
  'dangerHigh',
  'aLeft',
  'bLeft',
  'aRight',
  'bRight',
  'aLeftExp',
  'bLeftExp',
  'aRightExp',
  'bRightExp',
  'safeFee',
  'capFee',
] as const satisfies readonly (keyof SpryFeeParams)[];
const BIGINT_FIELD_INDICES = new Set([10, 11, 12, 13]);

interface Row {
  kind: string;
  tier: number;
  a: number;
  b: number;
  valueStr: string;
}

function loadRows(): Row[] {
  const csv = readFileSync(new URL('./fixtures/contract-fees.csv', import.meta.url), 'utf8');
  const rows: Row[] = [];
  for (const line of csv.split('\n')) {
    if (!line || line.startsWith('kind,')) continue;
    const parts = line.split(',');
    if (parts.length !== 5) throw new Error(`malformed fixture row: ${line}`);
    const [kind, tier, a, b, valueStr] = parts as [string, string, string, string, string];
    rows.push({ kind, tier: Number(tier), a: Number(a), b: Number(b), valueStr });
  }
  return rows;
}

const ROWS = loadRows();
const byKind = (kind: string) => ROWS.filter((r) => r.kind === kind);

describe('contract differential: fixture sanity', () => {
  it('loaded a non-trivial grid covering all tiers and kinds', () => {
    expect(ROWS.length).toBeGreaterThan(2_000);
    expect(new Set(ROWS.map((r) => r.tier))).toEqual(new Set([0, 1, 2, 3, 4]));
    for (const kind of ['param', 'fee', 'zone', 'marg', 'disp']) {
      expect(byKind(kind).length).toBeGreaterThan(0);
    }
  });
});

describe('contract differential: tierParams (exact)', () => {
  it('every cached coefficient matches the on-chain value', () => {
    const params = byKind('param');
    expect(params.length).toBe(16 * 5);
    for (const row of params) {
      const field = PARAM_FIELDS[row.a];
      if (!field) throw new Error(`bad param field index ${row.a}`);
      const cached = TIER_PARAMS[tierFromIndex(row.tier)][field];
      const expected = BIGINT_FIELD_INDICES.has(row.a) ? BigInt(row.valueStr) : Number(row.valueStr);
      expect(cached, `tier ${row.tier} field ${field}`).toBe(expected);
    }
  });
});

describe('contract differential: feeForDelta', () => {
  it('matches on-chain (exact outside danger, within tolerance inside)', () => {
    let maxDiff = 0;
    let exact = 0;
    const mismatches: string[] = [];
    for (const row of byKind('fee')) {
      const params = TIER_PARAMS[tierFromIndex(row.tier)];
      const expected = Number(row.valueStr);
      const actual = feeForDelta(row.a, params);
      const diff = Math.abs(actual - expected);
      if (diff === 0) exact++;
      maxDiff = Math.max(maxDiff, diff);
      const allowed = zoneOf(row.a, params) === SpryZone.DANGER ? DANGER_TOLERANCE_PIPS : 0;
      if (diff > allowed) mismatches.push(`tier ${row.tier} delta ${row.a}: js ${actual} vs sol ${expected}`);
    }
    const total = byKind('fee').length;
    // eslint-disable-next-line no-console
    console.log(`feeForDelta: ${total} points, ${exact} exact, maxDiff ${maxDiff} pips`);
    expect(mismatches.slice(0, 10)).toEqual([]);
  });
});

describe('contract differential: marginalFee', () => {
  it('matches on-chain within tolerance', () => {
    let maxDiff = 0;
    let exact = 0;
    const mismatches: string[] = [];
    for (const row of byKind('marg')) {
      const params = TIER_PARAMS[tierFromIndex(row.tier)];
      const expected = Number(row.valueStr);
      const actual = marginalFee(row.a, row.b, params);
      const diff = Math.abs(actual - expected);
      if (diff === 0) exact++;
      maxDiff = Math.max(maxDiff, diff);
      if (diff > DANGER_TOLERANCE_PIPS) {
        mismatches.push(`tier ${row.tier} (${row.a} -> ${row.b}): js ${actual} vs sol ${expected}`);
      }
    }
    const total = byKind('marg').length;
    // eslint-disable-next-line no-console
    console.log(`marginalFee: ${total} pairs, ${exact} exact, maxDiff ${maxDiff} pips`);
    expect(mismatches.slice(0, 10)).toEqual([]);
  });
});

describe('contract differential: zone / dispatch labels (exact)', () => {
  it('zoneOf matches on-chain zone ids', () => {
    for (const row of byKind('zone')) {
      const params = TIER_PARAMS[tierFromIndex(row.tier)];
      expect(ZONE_INDEX[zoneOf(row.a, params)], `tier ${row.tier} delta ${row.a}`).toBe(
        Number(row.valueStr),
      );
    }
  });

  it('dispatchCase matches on-chain case ids', () => {
    for (const row of byKind('disp')) {
      expect(DISPATCH_CASE_INDEX[dispatchCase(row.a, row.b)], `(${row.a} -> ${row.b})`).toBe(
        Number(row.valueStr),
      );
    }
  });
});
