import { readFileSync } from 'node:fs';
import { describe, it, expect } from 'vitest';
import { getAddress } from 'viem';
import { poolId, type Address, type PoolKey } from '../src/index';

// Differential test: poolId() vs the real on-chain PoolIdLibrary.toId.
// The fixture is generated by tools/contract-diff/script/DumpPoolIds.s.sol.
const csv = readFileSync(new URL('./fixtures/pool-ids.csv', import.meta.url), 'utf8');

describe('poolId vs on-chain PoolIdLibrary.toId', () => {
  it('matches the contract for every fixture key', () => {
    const rows = csv.trim().split('\n').slice(1); // drop header
    expect(rows.length).toBeGreaterThanOrEqual(5);
    for (const row of rows) {
      const parts = row.split(',');
      if (parts.length !== 7) throw new Error(`malformed fixture row: ${row}`);
      const [index, c0, c1, fee, ts, hooks, id] = parts as [string, string, string, string, string, string, string];
      const key: PoolKey = {
        currency0: getAddress(c0) as Address,
        currency1: getAddress(c1) as Address,
        fee: Number(fee),
        tickSpacing: Number(ts),
        hooks: getAddress(hooks) as Address,
      };
      expect(poolId(key).toLowerCase(), `key ${index}`).toBe(id.toLowerCase());
    }
  });
});
