// This is just an array of the app's defined paths that can be used in our Cloudflare Functions.
// Do not add any imports to this file.
// The array is kept up to date via the tests in src/pages/paths.test.ts

export const paths = [
  '/',
  '/explore',
  '/explore',
  '/explore/tokens/:chainName/:tokenAddress',
  '/tokens',
  '/tokens/:chainName',
  '/tokens/:chainName/:tokenAddress',
  '/explore/pools/:chainName/:poolAddress',
  '/vote/*',
  '/create-proposal',
  '/send',
  '/swap',
  '/portfolio',
  '/portfolio/tokens',
  '/portfolio/pools',
  '/portfolio/defi',
  '/portfolio/nfts',
  '/portfolio/activity',
  '/portfolio/:walletAddress',
  '/portfolio/:walletAddress/tokens',
  '/portfolio/:walletAddress/pools',
  '/portfolio/:walletAddress/defi',
  '/portfolio/:walletAddress/nfts',
  '/portfolio/:walletAddress/activity',
  '/positions',
  '/positions/add',
  '/positions/add/new',
  '/positions/add/:chainName/:poolAddress',
  '/positions/create',
  '/positions/v4/:chainName/:tokenId',
  '/increase',
  '/portfolio',
  '/portfolio/tokens',
  '/portfolio/pools',
  '/portfolio/defi',
  '/portfolio/nfts',
  '/portfolio/activity',
  '/auth/passkey/extension',
  '/manage/passkey/:walletAddress',
  '/extension/uninstall',
  '/wrapped',
  '/preview',
  '/spry',
]
